version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html/marketingFront
hooks:
  BeforeInstall:
    - location: scripts/kill_container.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/build.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
    - location: scripts/create_test_db.sh
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 300
      runas: root
