version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - $(aws ecr get-login --no-include-email | sed 's|https://||')
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t marketingfront:dev .
      - docker run -d -v ${PWD}:/app -v /app/node_modules -p 4201:4200 --name foo --rm example:dev
  post_build:
    commands:
      - echo Build completed on `date`
      # - echo Pushing the Docker image...
      # - docker push 119156810189.dkr.ecr.eu-west-1.amazonaws.com/marketing:latest
